services:
  web:
    build: .
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python /code/educa/manage.py migrate
  web_run:
    extends:
      service: web
    command: python /code/educa/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - web_migrate
